### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by YadiHe** [JiayuanWang-JW/DC-cycleGAN#1]
ERROR: Could not find a version that satisfies the requirement DeepKnockoffs==0.1.0 (from versions: none)
ERROR: No matching distribution found for DeepKnockoffs==0.1.0

Please help me

**Comment by JiayuanWang-JW** [comment]
Please use the Python 3.6 version. If your python version is too high. Maybe you will meet the environment issue.

**Comment by YadiHe** [comment]
> Please use the Python 3.6 version. If your python version is too high. Maybe you will meet the environment issue.

May I ask which version you have? My version Python 3.6.8

**Comment by JiayuanWang-JW** [comment]
3..6.13
pip install DeepKnockoffs==0.1.0 
This command is work for me.

**Comment by YadiHe** [comment]
> 3..6.13 pip install DeepKnockoffs==0.1.0 This command is work for me.

It's still giving me an error.
I'm trying to think of something else. Thanks.
