### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by tdktrang** [JiayuanWang-JW/DC-cycleGAN#2]
Hi, I want to download the dataset but the original https://github.com/ChengBinJin/MRI-to-CT-DCNN-TensorFlow not available anymore. Can you share it to me? Thank you!!! my email is tdktrang.ise@gmail.com

**Comment by JiayuanWang-JW** [comment]
Sorry, I can't do that. Please contact the dataset owner. I do not have a right to distribute the dataset because I am not the owner. That is why I didn't upload the dataset by myself.

**Comment by tdktrang** [comment]
thank you for your response!!

**Comment by pranotosh2** [comment]
Hi, Hope you are well.
Can you explain the dataset structure.
Please
