### ISSUE TITLE
code

### ISSUE THREAD

**Issue by wl989898** [JiayuanWang-JW/DC-cycleGAN#3]
How is the DC loss reflected in the code, and why can't I find the DC loss function in the discriminator

**Comment by JiayuanWang-JW** [comment]
[SSIM loss usage](https://github.com/JiayuanWang-JW/DC-cycleGAN/blob/main/DC-CycleGAN.py#L308). The goals of generators and discriminators are different. It doesn't make sense to use the same function for both of them. We need to focus on the specific tasks to design the loss function.

**Comment by wl989898** [comment]
Hi, I mean the innovation of the code is DC (Dual contrast loss), You mentioned in your paper that "each discriminator includes a DC loss that leverage the advantages of samples from the source domain as negative samples to enforce the synthesized images falling far away from the source domain. " Why didn't I find this DC loss in the discriminator in the code,where is it specifically reflected.Thank you!

**Comment by JiayuanWang-JW** [comment]
[D_A](image_array_mri) and [D_B](https://github.com/JiayuanWang-JW/DC-cycleGAN/blob/main/DC-CycleGAN.py#L362) are considered a DC loss for each discriminator. 

I hope this can figure out your confusion.
